# NumPy Pair Problem

For today's pair, we will use NumPy to complete the following tasks consecutively.

In [101]:
import numpy as np

# Set random seed so that results are reproducible
np.random.seed(0)

### 1. Generate three separate 1-dimensional arrays of 10,000 elements each.
* Array 1 should contain numbers randomly drawn from the uniform distribution between 1 and 100
* Array 2 should contain numbers randomly drawn from the normal distribution, with a mean of 0 and a standard deviation of 1
* Array 3 should contain numbers randomly drawn from the binomial distribution, where n=10 and p=0.5

In [102]:
array1 = np.random.uniform(1, 100, 10000)
array2 = np.random.normal(0, 1, 10000)
array3 = np.random.binomial(10, 0.5, 10000)
array1.shape

(10000,)

### 2. For each array, randomly sample 1,000 rows without replacement. (hint: `np.random.choice()`)


In [103]:
s1 = np.random.choice(array1, 1000)
s2 = np.random.choice(array2, 1000)
s3 = np.random.choice(array3, 1000)

### 3. For each of the three samples:  
- Calculate the mean, median, and standard deviation
- Find the index and the value of the largest element (hint: `np.argmax()`)  
- Find the value of the 75th percentile (hint: `np.percentile()`)  

In [104]:
np.mean(s1)
np.median(s1)
np.std(s1)
np.argmax(s1)
np.percentile(s1, 75)

np.mean(s2)
np.median(s2)
np.std(s2)
np.argmax(s2)
np.percentile(s2, 75)

np.mean(s3)
np.median(s3)
np.std(s3)
np.argmax(s3)
np.percentile(s3, 75)

6.0

### 4. Sort each of the three samples in increasing order, then combine them together to create a 1,000 by 3 array. (hint: `np.sort()` and `np.stack()`). Now, check the shape of the array.

In [105]:
s1 = np.sort(s1)
s2 = np.sort(s2)
s3 = np.sort(s3)

In [106]:
stack = np.stack((s1, s2, s3) , axis = 1)

### 5. Replace all negative values with 0. Replace all values that exceed 10 with 10.

In [107]:

stack = np.where(stack < 0, 0, stack)
stack = np.where(stack > 10,10,stack)
stack

array([[ 1.01488773,  0.        ,  1.        ],
       [ 1.06575764,  0.        ,  1.        ],
       [ 1.12840798,  0.        ,  1.        ],
       ...,
       [10.        ,  2.71614524,  9.        ],
       [10.        ,  2.76054867, 10.        ],
       [10.        ,  3.22050179, 10.        ]])

### 6. Subtract 5 from all values that exceed 5. (hint: `np.where()`)

In [108]:
np.where(stack > 5, stack - 5,stack)

array([[1.01488773, 0.        , 1.        ],
       [1.06575764, 0.        , 1.        ],
       [1.12840798, 0.        , 1.        ],
       ...,
       [5.        , 2.71614524, 4.        ],
       [5.        , 2.76054867, 5.        ],
       [5.        , 3.22050179, 5.        ]])

In [109]:
stack.shape

(1000, 3)

### 7. Produce a fourth column that is the sum of the first two columns.  (hint: `np.hstack()`). Now check the new shape of the array.

In [110]:
col4 = stack[:, 0] + stack[:, 1]

stack = np.hstack((stack , col4.reshape(1000,1)))
stack

array([[ 1.01488773,  0.        ,  1.        ,  1.01488773],
       [ 1.06575764,  0.        ,  1.        ,  1.06575764],
       [ 1.12840798,  0.        ,  1.        ,  1.12840798],
       ...,
       [10.        ,  2.71614524,  9.        , 12.71614524],
       [10.        ,  2.76054867, 10.        , 12.76054867],
       [10.        ,  3.22050179, 10.        , 13.22050179]])

### 8. Use broadcasting to add 1 to each element of the first column, 2 to each element of the second column, 3 to each element of the third column, and 4 to each element of the fourth column.

In [111]:
stack.shape

(1000, 4)

In [112]:
stack = stack +np.array([1,2,3,4])
stack

array([[ 2.01488773,  2.        ,  4.        ,  5.01488773],
       [ 2.06575764,  2.        ,  4.        ,  5.06575764],
       [ 2.12840798,  2.        ,  4.        ,  5.12840798],
       ...,
       [11.        ,  4.71614524, 12.        , 16.71614524],
       [11.        ,  4.76054867, 13.        , 16.76054867],
       [11.        ,  5.22050179, 13.        , 17.22050179]])

### 9. Matrix multiply this 1000x4 array by a 4x1 array of ones. How many unique values are in the resulting product?  (hint: `np.unique()`)

In [113]:
stack = np.dot(stack , np.ones(4))


In [117]:
np.unique(stack).shape[0]

587

# Thank You